#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

CONF="displaydash"

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/displaydash --config "$CONF"
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    return 0
}

reload_service() {
    restart
}
